name: Generate and Deploy Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r report/requirements.txt  # Assuming you have a requirements.txt

      - name: Run script and generate report
        run: |
          python report/report.py  # This should generate an HTML file

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report/
          publish_branch: gh-pages
